Disable Actions in RomBrowser ContextMenu when not needed
Rosalie241/RMG pull request #24
Opened 2022-01-04 17:32 UTC by JakobDev

If no ROM is selected, the Actions that refer to a selected ROM are disabled now. This also fixes a Crash when Play Game is clicked without a ROM selected.

2022-01-04 23:11 UTC, Rosalie241 commented
Wouldn't code like this work better and make more sense? As-in just don't show the popup when there's nothing selected.
```cpp
void RomBrowserWidget::customContextMenuRequested(QPoint position)
{
    if (this->selectedIndexes().count() > 0)
    {
        this->contextMenu->popup(this->viewport()->mapToGlobal(position));
    }
}
```

2022-01-05 14:17 UTC, JakobDev commented
1. The context menu contains 2 Actions (Refresh and choose ROM Directory) which doesn't depends on a selected Game.
2. Showing a context menu with disabled Actions, is what most programs do, so it's the behavior that a User expects.

2022-01-05 15:28 UTC, Rosalie241 commented
> 1. The context menu contains 2 Actions (Refresh and choose ROM Directory) which doesn't depends on a selected Game.
> 
> 2. Showing a context menu with disabled Actions, is what most programs do, so it's the behavior that a User expects.

Fair, if you fix my nitpick, I'll merge it, thank you ❤️

2022-01-05 15:29 UTC, Rosalie241 requested changes

2022-01-05 20:28 UTC, JakobDev commented on Source/RMG/UserInterface/Widget/RomBrowserWidget.cpp
> +    bool enabled =  this->selectedIndexes().count() > 0;
Done

2022-01-05 21:14 UTC, merged

2022-01-05 21:14 UTC, Rosalie241 commented
Thank you :heart: